package com.webpro.player.desktop.ui

import com.webpro.player.domain.model.AppError
import com.webpro.player.player.PlayerError

/** User-facing texts of the Windows app (Spanish). */
object S {
    const val APP_NAME = "WEBPRO PLAYER"
    const val TAGLINE = "Tu servicio IPTV, ahora en tu PC"

    const val RETRY = "Reintentar"
    const val BACK = "Volver"
    const val CANCEL = "Cancelar"
    const val DELETE = "Eliminar"
    const val REFRESH = "Actualizar"
    const val CLEAR = "Borrar"
    const val CLOSE = "Cerrar"
    const val ADD_FAVORITE = "Añadir a favoritos"
    const val REMOVE_FAVORITE = "Quitar de favoritos"
    const val ERROR_TITLE = "Algo no salió como esperábamos"
    const val EMPTY_TITLE = "No hay nada por aquí"
    const val CATALOG_EMPTY = "No hay contenido en esta categoría o con ese nombre. Prueba otra categoría o cambia la búsqueda."
    const val ALL = "Todos"
    const val FAVORITES_CATEGORY = "★ Favoritos"

    // Login
    const val LOGIN_TITLE = "Conecta tu servicio"
    const val LOGIN_SUBTITLE = "Introduce los datos de acceso que te facilitó tu proveedor IPTV."
    const val LOGIN_HERO_TITLE = "Tu televisión, películas y series en un solo lugar."
    const val LOGIN_HERO_MESSAGE = "WEBPRO PLAYER es un reproductor compatible con la API Xtream Codes. " +
        "Conecta tu propio servicio y disfrútalo en tu ordenador con la potencia del motor VLC."
    const val LOGIN_SERVER = "DNS / URL del servidor"
    const val LOGIN_SERVER_HINT = "http://servidor.com:8080"
    const val LOGIN_USER = "Usuario"
    const val LOGIN_PASSWORD = "Contraseña"
    const val LOGIN_REMEMBER = "Recordar conexión"
    const val LOGIN_CONNECT = "CONECTAR"
    const val LOGIN_CONNECTING = "CONECTANDO…"
    const val LOGIN_PRIVACY = "Tus credenciales se guardan cifradas con la protección de tu cuenta de Windows y solo se envían a tu servidor."
    const val FIELD_REQUIRED = "Este campo es obligatorio"
    const val FIELD_INVALID_URL = "Introduce una dirección válida, por ejemplo http://servidor.com:8080"
    const val FIELD_SCHEME = "Solo se admiten direcciones http:// o https://"

    // Sections
    const val HOME = "Inicio"
    const val LIVE = "TV en vivo"
    const val MOVIES = "Películas"
    const val SERIES = "Series"
    const val FAVORITES = "Favoritos"
    const val SEARCH = "Búsqueda"
    const val SETTINGS = "Configuración"

    // Home
    fun greeting(user: String) = "Hola, $user"
    const val HOME_SUBTITLE = "¿Qué te apetece ver hoy?"
    const val TILE_LIVE = "Canales en directo"
    const val TILE_MOVIES = "Cine bajo demanda"
    const val TILE_SERIES = "Temporadas y episodios"
    const val TILE_FAVORITES = "Tu selección personal"
    const val TILE_SEARCH = "Encuentra cualquier título"
    const val TILE_SETTINGS = "Cuenta y preferencias"
    const val CONTINUE_WATCHING = "Continuar viendo"
    const val MOVIE_LABEL = "Película"
    fun episodeLabel(season: Int, episode: Int) = "T$season · E$episode"

    // Catalog
    const val SEARCH_CHANNEL = "Buscar canal"
    const val SEARCH_MOVIE = "Buscar película"
    const val SEARCH_SERIES = "Buscar serie"
    const val NO_CHANNELS = "Sin canales"
    const val NO_MOVIES = "Sin películas"
    const val NO_SERIES = "Sin series"
    const val NOW_PLAYING = "Reproduciendo"
    fun items(count: Int) = if (count == 1) "1 elemento" else "$count elementos"

    // Details
    const val PLAY = "Reproducir"
    fun continueAt(time: String) = "Continuar ($time)"
    const val FROM_START = "Desde el inicio"
    const val NO_PLOT = "Sin descripción disponible."
    const val DIRECTOR = "Dirección"
    const val CAST = "Reparto"
    const val SEASONS = "Temporadas"
    fun seasonsCount(n: Int) = "$n temp."
    fun continueEpisode(s: Int, e: Int) = "Continuar T$s · E$e"
    fun playEpisode(s: Int, e: Int) = "Reproducir T$s · E$e"
    fun episodeTitle(n: Int, title: String) = "E$n · $title"
    const val NO_EPISODES = "Esta serie todavía no tiene episodios disponibles."

    // Favorites
    const val FAVORITES_SUBTITLE = "Guardados en este equipo"
    const val CHANNELS = "Canales"
    const val FAVORITES_EMPTY_TITLE = "Aún no tienes favoritos"
    const val FAVORITES_EMPTY = "Pulsa la estrella de un canal, o haz clic derecho en una película o serie, para añadirla aquí."

    // Search
    const val SEARCH_SUBTITLE = "Canales, películas y series de tu servicio"
    const val SEARCH_HINT = "¿Qué quieres ver?"
    const val SEARCH_IDLE_TITLE = "Busca en todo tu catálogo"
    const val SEARCH_IDLE = "Escribe al menos dos letras para buscar canales, películas y series."
    const val SEARCHING = "Buscando…"
    const val NO_RESULTS = "Sin resultados"
    fun noResultsFor(q: String) = "No encontramos nada para \"$q\"."

    // Player
    const val LIVE_BADGE = "EN VIVO"
    const val PAUSE = "Pausa"
    const val REWIND = "Retroceder 10 s (←)"
    const val FORWARD = "Avanzar 10 s (→)"
    const val PREV_CHANNEL = "Canal anterior (RePág)"
    const val NEXT_CHANNEL = "Canal siguiente (AvPág)"
    const val PREV_EPISODE = "Episodio anterior"
    const val NEXT_EPISODE = "Episodio siguiente"
    const val CHANNEL_LIST = "Lista de canales (L)"
    const val MUTE = "Silenciar (M)"
    const val AUDIO_TRACK = "Pista de audio"
    const val SUBTITLES = "Subtítulos"
    const val ASPECT = "Formato de imagen"
    const val FULLSCREEN = "Pantalla completa (F)"
    const val EXIT_FULLSCREEN = "Salir de pantalla completa (Esc)"
    const val RECONNECTING = "Reconectando…"
    fun reconnectingAttempt(a: Int, m: Int) = "Reconectando… intento $a de $m"
    fun resumedFrom(t: String) = "Reanudando desde $t"
    const val PLAYER_ERROR_TITLE = "No se puede reproducir"
    const val ENGINE_MISSING = "No se encontró el motor de vídeo (libVLC). Reinstala WEBPRO PLAYER o instala VLC 3 de 64 bits."
    const val NO_AUDIO_TRACKS = "Sin pistas de audio"
    const val SHORTCUTS = "Espacio: pausa · ←/→: ±10 s · ↑/↓: volumen · RePág/AvPág: canal · F: pantalla completa · M: silencio · Esc: salir"

    // Settings
    const val ACCOUNT = "Cuenta"
    const val SERVER = "Servidor"
    const val STATUS = "Estado"
    const val EXPIRATION = "Vencimiento"
    const val CONNECTIONS = "Conexiones"
    const val REMEMBERED = "Conexión recordada"
    const val UNKNOWN = "Desconocido"
    const val UNLIMITED = "Sin fecha de vencimiento"
    const val PLAYBACK = "Reproducción"
    const val LIVE_FORMAT = "Formato de TV en vivo"
    const val LIVE_FORMAT_HELP = "Si un canal no carga, prueba otro formato. MPEG-TS ofrece el arranque más rápido; HLS se adapta mejor a conexiones inestables. Si el formato elegido falla, se prueba el otro automáticamente."
    const val FORMAT_AUTO = "Automático"
    const val FORMAT_HLS = "HLS (m3u8)"
    const val FORMAT_TS = "MPEG-TS (ts)"
    const val AUTOPLAY = "Reproducir el siguiente episodio"
    const val AUTOPLAY_HELP = "Al terminar un episodio comienza automáticamente el siguiente."
    const val HW_DECODING = "Aceleración por hardware (GPU)"
    const val HW_DECODING_HELP = "Decodifica el vídeo con la tarjeta gráfica (D3D11/DXVA2). Desactívala si ves la imagen verde, negra o con artefactos."
    const val BUFFER = "Búfer de red"
    const val BUFFER_HELP = "Más búfer = menos cortes en conexiones inestables, pero el canal tarda un poco más en arrancar."
    const val DATA = "Sesión y datos"
    const val LOGOUT = "Cerrar sesión"
    const val LOGOUT_CONFIRM = "Se cerrará la sesión y se olvidará la contraseña. Tus favoritos se conservarán."
    const val DELETE_ALL = "Eliminar configuración"
    const val DELETE_CONFIRM = "Se eliminarán el servidor, las credenciales, los favoritos, el historial y las preferencias de este equipo. Esta acción no se puede deshacer."
    const val DATA_HELP = "Cerrar sesión conserva tus favoritos. Eliminar configuración borra todos los datos guardados por la aplicación."
    const val ABOUT = "Información"
    const val VERSION = "Versión"
    const val ENGINE = "Motor de reproducción"
    const val ABOUT_TEXT = "WEBPRO PLAYER es un reproductor multimedia. No incluye, vende ni distribuye canales, listas ni contenido de ningún tipo: el usuario debe disponer de su propio servicio IPTV compatible con Xtream Codes y es responsable del contenido al que accede."
    const val YES = "Sí"
    const val NO = "No"

    fun error(error: AppError): String = when (error) {
        AppError.InvalidCredentials -> "Usuario o contraseña incorrectos. Revisa tus datos e inténtalo de nuevo."
        AppError.AccountExpired -> "Tu suscripción ha caducado. Contacta con tu proveedor de servicio."
        AppError.AccountDisabled -> "Tu cuenta está desactivada. Contacta con tu proveedor de servicio."
        AppError.NoConnection -> "No hay conexión a Internet. Comprueba tu red e inténtalo de nuevo."
        AppError.Timeout -> "El servidor tardó demasiado en responder. Inténtalo de nuevo en unos segundos."
        AppError.ServerUnreachable -> "No se pudo contactar con el servidor. Revisa la dirección (DNS/URL) y el puerto."
        is AppError.Http -> "El servidor respondió con un error (${error.code}). Inténtalo más tarde."
        AppError.InvalidResponse -> "La dirección no corresponde a un servidor compatible con Xtream Codes."
        AppError.InvalidUrl -> "La dirección del servidor no es válida."
        AppError.NotFound -> "El contenido solicitado no está disponible en el servidor."
        AppError.NotLoggedIn -> "Tu sesión ha finalizado. Vuelve a conectar tu servicio."
        is AppError.Unknown -> "Ocurrió un error inesperado. Inténtalo de nuevo."
    }

    fun playerError(error: PlayerError): String = when (error) {
        PlayerError.Timeout -> "El servidor tardó demasiado en enviar la señal."
        PlayerError.ConnectionReset -> "La conexión con el servidor se interrumpió."
        PlayerError.Network -> "No se puede conectar con el servidor. Comprueba tu conexión: la reproducción se reanudará sola cuando vuelva."
        PlayerError.BehindLiveWindow -> "Se perdió la sincronización con la emisión en directo."
        PlayerError.Unauthorized -> "El servidor rechazó tus credenciales (401). Vuelve a iniciar sesión."
        PlayerError.Forbidden -> "Acceso denegado (403). Puede que tu suscripción no incluya este contenido o hayas alcanzado el máximo de conexiones simultáneas."
        PlayerError.NotFound -> "Este contenido no está disponible en el servidor (404)."
        is PlayerError.ServerError -> "El servidor respondió con un error (${error.httpCode})."
        PlayerError.Source -> "El servidor no envió una señal reproducible para este contenido."
        PlayerError.Decoder -> "No se pudo iniciar el motor de vídeo."
        PlayerError.Unknown -> "Ocurrió un error inesperado durante la reproducción."
    }
}
