import type { CategoryId, FeatureGroup, ProjectType } from './types';

/** Construye un grupo de funcionalidades. Un "+" inicial marca la funcionalidad como avanzada. */
function g(name: string, ...items: string[]): FeatureGroup {
  return {
    name,
    items: items.map((raw) =>
      raw.startsWith('+') ? { label: raw.slice(1).trim(), advanced: true } : { label: raw.trim() },
    ),
  };
}

export const CATEGORIES: { id: CategoryId; label: string; description: string }[] = [
  { id: 'web', label: 'Web', description: 'Sitios corporativos, landings, blogs y portales.' },
  { id: 'ecommerce', label: 'E-commerce', description: 'Tiendas, marketplaces, suscripciones y membresías.' },
  { id: 'sistemas', label: 'Sistemas', description: 'CRM, ERP, POS, reservas, facturación y gestión.' },
  { id: 'saas', label: 'SaaS', description: 'Productos multiusuario, multiempresa, APIs y planes.' },
  { id: 'apps', label: 'Aplicaciones', description: 'PWA, apps web, Android, Android TV y paneles.' },
  { id: 'custom', label: 'Personalizado', description: 'Cualquier otro tipo de proyecto.' },
];

// ---------------------------------------------------------------------------
// Bloques reutilizables
// ---------------------------------------------------------------------------
const AUTH = [
  'Registro con verificación de email',
  'Inicio de sesión',
  'Recuperación de contraseña por email',
  'Perfil de usuario editable',
  '+Autenticación en dos pasos (TOTP)',
  '+Login social con Google',
];
const ADMIN_CORE = [
  'Dashboard con KPIs calculados desde la base de datos',
  'Gestión de usuarios (alta, edición, bloqueo)',
  'Roles y permisos',
  'Configuración general del sistema',
  'Logs de actividad y auditoría',
];
const CMS_ADMIN = [
  'Panel de administración de contenidos',
  'Editor de páginas y secciones',
  'Biblioteca de medios con optimización de imágenes',
  'Gestión de menús de navegación',
  'Configuración de SEO por página',
];
const SHOP_CLIENT = [
  ...AUTH.slice(0, 4),
  'Catálogo de productos',
  'Categorías y subcategorías',
  'Búsqueda de productos',
  'Filtros (precio, categoría, atributos) y ordenación',
  'Ficha de producto con galería y variantes',
  'Carrito persistente',
  'Checkout con dirección y método de envío',
  'Pago online',
  'Historial y detalle de pedidos',
  'Favoritos / lista de deseos',
  'Cupones de descuento',
  'Reseñas y valoraciones',
  'Notificaciones por email del estado del pedido',
  '+Productos vistos recientemente y recomendados',
  '+Seguimiento del envío',
];
const SHOP_ADMIN = [
  'Dashboard de ventas (ingresos, pedidos, ticket medio, productos top)',
  'Gestión de productos y variantes',
  'Gestión de categorías',
  'Gestión de pedidos y estados',
  'Gestión de clientes',
  'Gestión de usuarios y roles',
  'Cupones y promociones',
  'Inventario con alertas de stock bajo',
  'Reportes exportables (CSV)',
  'Configuración de envíos, impuestos y pagos',
  'Logs de actividad',
  '+Devoluciones y reembolsos',
  '+Carritos abandonados',
];

// ---------------------------------------------------------------------------
// Catálogo
// ---------------------------------------------------------------------------
export const PROJECT_TYPES: ProjectType[] = [
  // ============================== WEB ==============================
  {
    id: 'corporate',
    label: 'Página corporativa',
    category: 'web',
    summary: 'Sitio institucional para presentar una empresa, sus servicios y captar contactos.',
    keywords: ['corporativa', 'corporativo', 'empresa', 'institucional', 'sitio web de', 'pagina web de', 'web de mi empresa'],
    needsDb: true,
    seo: 'high',
    roles: ['Visitante', 'Editor', 'Administrador'],
    featureGroups: [
      g('Sitio público', 'Inicio con propuesta de valor clara', 'Página de servicios con detalle por servicio', 'Página "Nosotros" con equipo', 'Casos de éxito / portafolio', 'Testimonios', 'Formulario de contacto con validación y anti-spam', 'Mapa y datos de contacto', '+Blog de noticias', '+Sitio multilenguaje'),
      g('Administración', ...CMS_ADMIN, 'Bandeja de mensajes de contacto', '+Gestión de ofertas de empleo'),
    ],
    integrations: ['email', 'google'],
    entities: ['users', 'pages', 'sections', 'services', 'team_members', 'testimonials', 'contact_messages', 'media', 'settings'],
    stackHint: 'Un sitio mayormente estático con CMS ligero: Next.js con renderizado estático/ISR o WordPress si el cliente necesita editar sin desarrolladores.',
    domainNotes: ['El rendimiento y el SEO son críticos: generar páginas estáticas cuando sea posible.', 'Formularios con protección anti-spam (honeypot + rate limiting) y aviso de privacidad.'],
  },
  {
    id: 'landing',
    label: 'Landing Page',
    category: 'web',
    summary: 'Página de conversión enfocada en una oferta concreta.',
    keywords: ['landing', 'pagina de aterrizaje', 'one page', 'onepage', 'captar leads', 'lanzamiento'],
    needsDb: true,
    seo: 'high',
    roles: ['Visitante', 'Administrador'],
    featureGroups: [
      g('Landing', 'Hero con titular, subtítulo y CTA principal', 'Sección de beneficios', 'Cómo funciona (pasos)', 'Prueba social: testimonios y logos', 'Tabla de precios o planes', 'Preguntas frecuentes (FAQ)', 'Formulario de captación de leads', 'CTA final y footer legal', '+Variantes A/B del titular', '+Contador regresivo de lanzamiento'),
      g('Administración', 'Panel protegido con listado de leads', 'Exportación de leads a CSV', 'Métricas de conversión (visitas vs. leads)', '+Edición de textos de la landing'),
    ],
    integrations: ['email', 'google', 'webhooks'],
    entities: ['leads', 'page_events', 'users'],
    stackHint: 'Next.js estático o Astro con un endpoint para leads; carga inicial mínima.',
    domainNotes: ['Objetivo principal: conversión. Cada sección debe empujar al CTA.', 'Lighthouse ≥ 95 en rendimiento en móvil.', 'Aviso de cookies y política de privacidad para la captación de datos.'],
  },
  {
    id: 'portfolio',
    label: 'Portafolio',
    category: 'web',
    summary: 'Portafolio profesional para mostrar proyectos y conseguir clientes.',
    keywords: ['portafolio', 'portfolio', 'mis trabajos', 'freelance', 'fotografo', 'diseñador'],
    needsDb: true,
    seo: 'high',
    roles: ['Visitante', 'Propietario'],
    featureGroups: [
      g('Sitio público', 'Inicio con presentación personal', 'Galería de proyectos filtrable por categoría', 'Página de detalle de proyecto (reto, solución, resultados)', 'Sobre mí / CV', 'Servicios', 'Formulario de contacto', '+Blog', '+Descarga de CV en PDF'),
      g('Administración', 'CRUD de proyectos con imágenes', 'Gestión de categorías', 'Bandeja de mensajes', 'Configuración de perfil y redes'),
    ],
    integrations: ['email'],
    entities: ['projects', 'project_images', 'categories', 'messages', 'settings', 'users'],
    stackHint: 'Next.js con generación estática y optimización de imágenes.',
    domainNotes: ['Las imágenes son protagonistas: formatos modernos (AVIF/WebP), lazy loading y tamaños responsivos.'],
  },
  {
    id: 'blog',
    label: 'Blog',
    category: 'web',
    summary: 'Blog con gestión de artículos, categorías y comentarios.',
    keywords: ['blog', 'articulos', 'bitacora', 'posts'],
    needsDb: true,
    seo: 'high',
    roles: ['Lector', 'Autor', 'Editor', 'Administrador'],
    featureGroups: [
      g('Lectores', 'Listado de artículos paginado', 'Artículo con tabla de contenidos y tiempo de lectura', 'Categorías y etiquetas', 'Búsqueda', 'Artículos relacionados', 'Comentarios moderados', 'Suscripción a newsletter', 'Feed RSS', '+Modo lectura'),
      g('Autores y editores', 'Editor de artículos enriquecido (Markdown o bloques)', 'Borradores, revisión y programación de publicación', 'Gestión de imágenes destacadas', 'Moderación de comentarios', 'SEO por artículo'),
      g('Administración', ...ADMIN_CORE.slice(0, 3), 'Estadísticas de lectura por artículo'),
    ],
    integrations: ['email', 'google'],
    entities: ['users', 'posts', 'categories', 'tags', 'post_tags', 'comments', 'subscribers', 'media'],
    stackHint: 'Next.js con ISR o WordPress; SEO técnico de primer nivel.',
    domainNotes: ['Schema.org Article/BlogPosting y migas de pan.', 'Comentarios con protección anti-spam y moderación.'],
  },
  {
    id: 'magazine',
    label: 'Revista digital',
    category: 'web',
    summary: 'Medio digital con secciones, autores y contenido destacado.',
    keywords: ['revista', 'periodico', 'noticias', 'medio digital', 'magazine'],
    needsDb: true,
    seo: 'high',
    roles: ['Lector', 'Suscriptor', 'Periodista', 'Editor jefe', 'Administrador'],
    featureGroups: [
      g('Lectores', 'Portada con destacados editoriales', 'Secciones temáticas', 'Página de autor', 'Artículo con multimedia', 'Búsqueda avanzada', 'Newsletter', '+Muro de pago / contenido premium', '+Ediciones o números'),
      g('Redacción', 'Flujo editorial: borrador → revisión → publicado', 'Programación de publicaciones', 'Gestión de portada', 'Asignación de autores', 'Gestión de medios'),
      g('Administración', ...ADMIN_CORE),
    ],
    integrations: ['email', 'google', 'stripe'],
    entities: ['users', 'articles', 'sections', 'authors', 'tags', 'issues', 'media', 'subscriptions'],
    stackHint: 'Next.js con ISR y caché agresiva en CDN; base de datos relacional.',
    domainNotes: ['Alto tráfico de lectura: caché por página y revalidación al publicar.', 'Schema.org NewsArticle y sitemap de noticias.'],
  },
  {
    id: 'directory',
    label: 'Directorio',
    category: 'web',
    summary: 'Directorio de negocios o profesionales con fichas, búsqueda y reseñas.',
    keywords: ['directorio', 'listado de negocios', 'guia de', 'paginas amarillas'],
    needsDb: true,
    seo: 'high',
    roles: ['Visitante', 'Propietario de ficha', 'Moderador', 'Administrador'],
    featureGroups: [
      g('Visitantes', 'Búsqueda por texto, categoría y ubicación', 'Fichas con datos, horario, fotos y mapa', 'Reseñas y valoraciones', 'Favoritos', '+Búsqueda en mapa'),
      g('Propietarios', ...AUTH.slice(0, 4), 'Alta y reclamación de ficha', 'Edición de ficha', 'Estadísticas de visitas', '+Planes destacados de pago'),
      g('Administración', 'Moderación de fichas y reseñas', 'Gestión de categorías y ubicaciones', ...ADMIN_CORE.slice(0, 2)),
    ],
    integrations: ['google', 'email', 'stripe'],
    entities: ['users', 'listings', 'categories', 'locations', 'reviews', 'favorites', 'claims', 'plans'],
    stackHint: 'Next.js + PostgreSQL (búsqueda de texto completo y, si aplica, PostGIS).',
    domainNotes: ['URLs amigables por categoría y ciudad.', 'Schema.org LocalBusiness en cada ficha.'],
  },
  {
    id: 'portal',
    label: 'Portal web',
    category: 'web',
    summary: 'Portal con contenidos, usuarios registrados y áreas privadas.',
    keywords: ['portal', 'intranet', 'comunidad', 'foro'],
    needsDb: true,
    seo: 'medium',
    roles: ['Visitante', 'Usuario registrado', 'Moderador', 'Administrador'],
    featureGroups: [
      g('Usuarios', ...AUTH, 'Área privada personalizada', 'Notificaciones internas', 'Búsqueda global', '+Foro o comunidad'),
      g('Contenido', 'Secciones y páginas', 'Noticias y anuncios', 'Documentos descargables con permisos'),
      g('Administración', ...ADMIN_CORE, ...CMS_ADMIN.slice(0, 2)),
    ],
    integrations: ['email', 'google'],
    entities: ['users', 'roles', 'pages', 'news', 'documents', 'notifications', 'audit_logs'],
    stackHint: 'Next.js o Laravel con base de datos relacional y control de acceso por roles.',
    domainNotes: ['Control de acceso granular a contenidos privados.'],
  },

  // ============================== E-COMMERCE ==============================
  {
    id: 'woocommerce',
    label: 'WooCommerce',
    category: 'ecommerce',
    summary: 'Tienda online sobre WordPress + WooCommerce.',
    keywords: ['woocommerce', 'woo commerce', 'wordpress tienda'],
    needsDb: true,
    seo: 'high',
    roles: ['Cliente', 'Gestor de tienda', 'Administrador'],
    featureGroups: [
      g('Cliente', ...SHOP_CLIENT),
      g('Administrador', ...SHOP_ADMIN),
      g('WordPress / WooCommerce', 'Tema hijo (child theme) a medida, sin modificar el core ni plugins de terceros', 'Plantillas de WooCommerce sobrescritas en el tema', 'Productos variables (atributos como talla y color)', 'Configuración de zonas y métodos de envío', 'Impuestos configurados según el país', 'Emails de WooCommerce personalizados', '+Plugin propio para lógica de negocio específica'),
    ],
    integrations: ['stripe', 'paypal', 'email'],
    entities: ['wp_posts (product, shop_order)', 'wp_postmeta', 'wc_orders (HPOS)', 'wc_order_items', 'wp_terms (categorías y atributos)', 'wp_users / wp_usermeta', 'wc_product_meta_lookup'],
    stackHint: 'WordPress + WooCommerce con tema hijo, PHP 8.2+, MySQL/MariaDB.',
    domainNotes: [
      'Usar hooks (actions/filters) y un tema hijo o plugin propio; nunca editar archivos del core de WordPress/WooCommerce.',
      'Activar HPOS (High-Performance Order Storage) y comprobar compatibilidad de plugins.',
      'Elegir plugins oficiales y mantenidos para pasarelas de pago; justificar cada plugin añadido.',
      'Entorno reproducible con Docker (wordpress + mysql) o wp-env y WP-CLI para la configuración.',
      'Caché de página, optimización de imágenes y limpieza de plugins innecesarios.',
    ],
  },
  {
    id: 'custom_store',
    label: 'Tienda personalizada',
    category: 'ecommerce',
    summary: 'E-commerce a medida con catálogo, carrito, checkout y panel administrativo.',
    keywords: ['tienda online', 'tienda virtual', 'ecommerce', 'e-commerce', 'vender productos', 'tienda de'],
    needsDb: true,
    seo: 'high',
    roles: ['Cliente', 'Gestor de tienda', 'Administrador'],
    featureGroups: [g('Cliente', ...SHOP_CLIENT), g('Administrador', ...SHOP_ADMIN)],
    integrations: ['stripe', 'email'],
    entities: ['users', 'addresses', 'products', 'product_variants', 'product_images', 'categories', 'inventory_movements', 'carts', 'cart_items', 'orders', 'order_items', 'payments', 'shipments', 'coupons', 'reviews', 'wishlists'],
    stackHint: 'Next.js + TypeScript + PostgreSQL + ORM con migraciones; pagos con la pasarela adecuada al país.',
    domainNotes: [
      'Los precios y totales se calculan SIEMPRE en el servidor; nunca confiar en importes enviados por el cliente.',
      'El stock se descuenta de forma transaccional al confirmar el pago (evitar sobreventa).',
      'Los pedidos guardan una copia de precio y nombre del producto en el momento de la compra.',
    ],
  },
  {
    id: 'marketplace',
    label: 'Marketplace',
    category: 'ecommerce',
    summary: 'Plataforma multivendedor con comisiones y pagos divididos.',
    keywords: ['marketplace', 'multivendedor', 'multi vendedor', 'vendedores', 'tipo amazon', 'tipo mercado libre'],
    needsDb: true,
    seo: 'high',
    roles: ['Comprador', 'Vendedor', 'Soporte', 'Administrador'],
    featureGroups: [
      g('Comprador', ...SHOP_CLIENT.slice(0, 14), 'Chat o mensajes con el vendedor', 'Disputas y reclamaciones'),
      g('Vendedor', 'Registro y verificación de vendedor (KYC básico)', 'Tienda/perfil público del vendedor', 'Gestión de productos e inventario propio', 'Gestión de pedidos propios', 'Balance, comisiones y liquidaciones', 'Estadísticas de ventas', '+Cupones propios'),
      g('Administrador', 'Aprobación de vendedores y productos', 'Configuración de comisiones por categoría', 'Gestión de disputas', 'Liquidaciones a vendedores', ...SHOP_ADMIN.slice(0, 1), ...ADMIN_CORE.slice(1)),
    ],
    integrations: ['stripe', 'mercadopago', 'email', 'webhooks'],
    entities: ['users', 'vendors', 'vendor_payouts', 'products', 'product_variants', 'categories', 'orders', 'sub_orders (por vendedor)', 'order_items', 'payments', 'commissions', 'disputes', 'messages', 'reviews'],
    stackHint: 'Next.js + PostgreSQL; pagos divididos con Stripe Connect o el equivalente de la pasarela elegida.',
    domainNotes: [
      'Un pedido con productos de varios vendedores se divide en sub-pedidos por vendedor.',
      'Pagos divididos mediante el producto de marketplace de la pasarela (p. ej., Stripe Connect); no retener fondos manualmente sin respaldo legal.',
      'Aislamiento estricto: un vendedor nunca accede a datos de otro.',
    ],
  },
  {
    id: 'dropshipping',
    label: 'Dropshipping',
    category: 'ecommerce',
    summary: 'Tienda que vende productos de proveedores que envían directamente al cliente.',
    keywords: ['dropshipping', 'drop shipping', 'proveedor envia'],
    needsDb: true,
    seo: 'high',
    roles: ['Cliente', 'Administrador'],
    featureGroups: [
      g('Cliente', ...SHOP_CLIENT),
      g('Administrador', ...SHOP_ADMIN.slice(0, 7), 'Gestión de proveedores', 'Importación de productos desde proveedor (CSV o API documentada)', 'Reenvío automático de pedidos al proveedor', 'Sincronización de stock y precios', 'Cálculo de margen por producto', 'Seguimiento de envíos del proveedor'),
    ],
    integrations: ['stripe', 'email', 'external_api', 'webhooks'],
    entities: ['products', 'suppliers', 'supplier_products', 'orders', 'supplier_orders', 'shipments', 'customers', 'sync_logs'],
    stackHint: 'Next.js o WooCommerce según necesidad de autogestión; colas para sincronizaciones.',
    domainNotes: ['Las sincronizaciones con proveedores corren en segundo plano con reintentos y registro.', 'Solo integrar APIs de proveedores documentadas; si no existen, usar importación CSV.'],
  },
  {
    id: 'digital_store',
    label: 'Tienda de productos digitales',
    category: 'ecommerce',
    summary: 'Venta de ebooks, cursos, plantillas, software o archivos descargables.',
    keywords: ['productos digitales', 'descargables', 'ebooks', 'plantillas', 'licencias', 'tienda digital'],
    needsDb: true,
    seo: 'high',
    roles: ['Cliente', 'Administrador'],
    featureGroups: [
      g('Cliente', ...AUTH.slice(0, 4), 'Catálogo con vista previa', 'Carrito y checkout', 'Pago online', 'Biblioteca de compras', 'Descargas con enlaces firmados y caducidad', 'Facturas descargables', 'Cupones', '+Claves de licencia'),
      g('Administrador', 'Gestión de productos y archivos', 'Ventas e ingresos', 'Clientes', 'Límites de descarga', 'Cupones', 'Reembolsos', ...ADMIN_CORE.slice(4)),
    ],
    integrations: ['stripe', 'paypal', 'email'],
    entities: ['users', 'products', 'product_files', 'orders', 'order_items', 'payments', 'download_tokens', 'licenses', 'coupons'],
    stackHint: 'Next.js + PostgreSQL + almacenamiento de objetos privado (S3 compatible) con URLs firmadas.',
    domainNotes: ['Los archivos se almacenan privados; la descarga se entrega con URL firmada temporal tras verificar la compra.'],
  },
  {
    id: 'services_store',
    label: 'Tienda de servicios',
    category: 'ecommerce',
    summary: 'Venta de servicios con paquetes, agenda y seguimiento.',
    keywords: ['venta de servicios', 'tienda de servicios', 'servicios profesionales', 'contratar servicios'],
    needsDb: true,
    seo: 'high',
    roles: ['Cliente', 'Profesional', 'Administrador'],
    featureGroups: [
      g('Cliente', ...AUTH.slice(0, 4), 'Catálogo de servicios con paquetes', 'Formulario de requisitos del servicio', 'Pago online o anticipo', 'Agenda de cita (si aplica)', 'Seguimiento del estado del servicio', 'Mensajería con el profesional', 'Valoraciones'),
      g('Administrador', 'Gestión de servicios y paquetes', 'Gestión de solicitudes/órdenes', 'Asignación a profesionales', 'Calendario', 'Pagos y facturación', ...ADMIN_CORE.slice(0, 2)),
    ],
    integrations: ['stripe', 'email', 'whatsapp'],
    entities: ['users', 'services', 'packages', 'service_orders', 'appointments', 'messages', 'payments', 'reviews'],
    stackHint: 'Next.js o Laravel con base de datos relacional.',
    domainNotes: ['Estados claros del servicio: solicitado → pagado → en curso → entregado → cerrado.'],
  },
  {
    id: 'subscriptions',
    label: 'Suscripciones',
    category: 'ecommerce',
    summary: 'Comercio con cobros recurrentes (cajas, productos o servicios por suscripción).',
    keywords: ['suscripcion', 'suscripciones', 'pago recurrente', 'mensualidad', 'caja mensual'],
    needsDb: true,
    seo: 'medium',
    roles: ['Suscriptor', 'Administrador'],
    featureGroups: [
      g('Suscriptor', ...AUTH.slice(0, 4), 'Selección de plan y periodicidad', 'Checkout con pago recurrente', 'Portal de suscripción: pausar, cambiar plan, cancelar', 'Historial de cobros y facturas', 'Actualización del método de pago', 'Notificaciones de renovación y cobro fallido'),
      g('Administrador', 'Gestión de planes y precios', 'Suscriptores y estados', 'Métricas MRR, churn y LTV', 'Gestión de cobros fallidos (dunning)', 'Cupones y periodos de prueba', ...ADMIN_CORE.slice(1, 3)),
    ],
    integrations: ['stripe', 'email', 'webhooks'],
    entities: ['users', 'plans', 'prices', 'subscriptions', 'invoices', 'payments', 'coupons', 'webhook_events'],
    stackHint: 'Next.js + PostgreSQL + Stripe Billing (fuente de verdad del estado de la suscripción vía webhooks).',
    domainNotes: ['El estado de la suscripción se sincroniza desde los webhooks de la pasarela, no se calcula en el cliente.'],
  },
  {
    id: 'memberships',
    label: 'Membresías',
    category: 'ecommerce',
    summary: 'Sitio de membresías con niveles de acceso a contenido o beneficios.',
    keywords: ['membresia', 'membresias', 'miembros', 'contenido exclusivo', 'club'],
    needsDb: true,
    seo: 'medium',
    roles: ['Visitante', 'Miembro', 'Administrador'],
    featureGroups: [
      g('Miembros', ...AUTH.slice(0, 4), 'Niveles de membresía con beneficios', 'Pago recurrente', 'Contenido restringido por nivel', 'Área de miembro con beneficios activos', 'Gestión de la membresía (cambio de nivel, cancelación)', '+Comunidad / foro privado', '+Eventos exclusivos'),
      g('Administrador', 'Gestión de niveles y reglas de acceso', 'Gestión de miembros', 'Contenido restringido', 'Métricas de retención', ...ADMIN_CORE.slice(1, 3)),
    ],
    integrations: ['stripe', 'email'],
    entities: ['users', 'membership_levels', 'memberships', 'content_items', 'access_rules', 'payments'],
    stackHint: 'Next.js + PostgreSQL + Stripe Billing, o WordPress con un plugin de membresías mantenido.',
    domainNotes: ['El control de acceso al contenido se verifica en el servidor en cada petición.'],
  },

  // ============================== SISTEMAS ==============================
  {
    id: 'crm',
    label: 'CRM',
    category: 'sistemas',
    summary: 'Gestión de clientes, oportunidades y actividades comerciales.',
    keywords: ['crm', 'clientes potenciales', 'embudo de ventas', 'pipeline', 'gestion de clientes'],
    needsDb: true,
    seo: 'low',
    roles: ['Vendedor', 'Gerente comercial', 'Administrador'],
    featureGroups: [
      g('Comercial', 'Contactos y empresas', 'Oportunidades en pipeline Kanban por etapas', 'Actividades: llamadas, reuniones, tareas', 'Notas e historial por contacto', 'Importación de contactos desde CSV', 'Búsqueda y filtros guardados', 'Etiquetas y segmentos', '+Plantillas de email', '+Cotizaciones en PDF'),
      g('Gestión', 'Dashboard de ventas y previsión', 'Rendimiento por vendedor', 'Reportes exportables', 'Asignación de leads'),
      g('Administración', ...ADMIN_CORE, 'Campos personalizados'),
    ],
    integrations: ['email', 'google', 'whatsapp', 'webhooks'],
    entities: ['users', 'teams', 'contacts', 'companies', 'deals', 'pipeline_stages', 'activities', 'notes', 'tags', 'custom_fields', 'audit_logs'],
    stackHint: 'Next.js o Laravel + PostgreSQL; tablas con paginación del lado servidor.',
    domainNotes: ['Visibilidad de registros por propietario/equipo según rol.', 'Historial inmutable de cambios relevantes (auditoría).'],
  },
  {
    id: 'erp',
    label: 'ERP',
    category: 'sistemas',
    summary: 'Planificación de recursos empresariales: compras, ventas, inventario y contabilidad.',
    keywords: ['erp', 'planificacion de recursos', 'compras y ventas', 'gestion integral'],
    needsDb: true,
    seo: 'low',
    roles: ['Operador', 'Contador', 'Jefe de almacén', 'Gerente', 'Administrador'],
    featureGroups: [
      g('Ventas', 'Clientes', 'Cotizaciones → pedidos → facturas', 'Listas de precios'),
      g('Compras', 'Proveedores', 'Órdenes de compra', 'Recepción de mercancía'),
      g('Inventario', 'Productos y almacenes', 'Movimientos de stock con trazabilidad', 'Ajustes e inventarios físicos', '+Lotes y fechas de vencimiento'),
      g('Finanzas', 'Cuentas por cobrar y por pagar', 'Registro de pagos', '+Plan de cuentas y asientos contables', 'Reportes financieros'),
      g('Administración', ...ADMIN_CORE, '+Multi-sucursal'),
    ],
    integrations: ['email', 'webhooks', 'external_api'],
    entities: ['users', 'roles', 'customers', 'suppliers', 'products', 'warehouses', 'stock_movements', 'quotes', 'sales_orders', 'invoices', 'purchase_orders', 'payments', 'accounts', 'journal_entries'],
    stackHint: 'Laravel o Node.js/NestJS + PostgreSQL con transacciones y módulos bien separados.',
    domainNotes: ['Operaciones contables y de inventario siempre en transacciones ACID.', 'Documentos con numeración consecutiva e inmutables una vez emitidos (anular en lugar de borrar).'],
  },
  {
    id: 'pos',
    label: 'POS',
    category: 'sistemas',
    summary: 'Punto de venta para tiendas físicas o restaurantes.',
    keywords: ['pos', 'punto de venta', 'caja registradora', 'tpv'],
    needsDb: true,
    seo: 'low',
    roles: ['Cajero', 'Supervisor', 'Administrador'],
    featureGroups: [
      g('Caja', 'Venta rápida con búsqueda y lector de código de barras', 'Múltiples métodos de pago y pagos mixtos', 'Descuentos autorizados', 'Ticket imprimible / enviado por email', 'Apertura y cierre de caja con arqueo', 'Devoluciones', '+Modo sin conexión con sincronización'),
      g('Gestión', 'Productos, precios e impuestos', 'Inventario', 'Clientes', 'Reportes de ventas por turno, cajero y producto'),
      g('Administración', ...ADMIN_CORE, '+Multi-tienda'),
    ],
    integrations: ['email'],
    entities: ['users', 'stores', 'registers', 'register_sessions', 'products', 'categories', 'sales', 'sale_items', 'payments', 'returns', 'customers', 'stock_movements'],
    stackHint: 'PWA con React/Next.js + backend Node.js + PostgreSQL; diseño optimizado para pantallas táctiles.',
    domainNotes: ['Interfaz táctil con objetivos grandes y atajos de teclado.', 'Arqueo de caja: diferencias registradas y auditadas.'],
    pwa: true,
  },
  {
    id: 'bookings',
    label: 'Sistema de reservas',
    category: 'sistemas',
    summary: 'Reservas de habitaciones, citas, mesas o recursos con disponibilidad en tiempo real.',
    keywords: ['reservas', 'reserva', 'citas', 'agenda', 'hotel', 'booking', 'turnos', 'agendamiento'],
    needsDb: true,
    seo: 'medium',
    roles: ['Cliente', 'Recepción / Staff', 'Administrador'],
    featureGroups: [
      g('Cliente', 'Búsqueda de disponibilidad por fechas', 'Selección de recurso (habitación, servicio, profesional)', 'Reserva con datos del huésped/cliente', 'Pago o depósito online', 'Confirmación por email', 'Gestión de la reserva: modificar o cancelar según política', ...AUTH.slice(0, 3), '+Recordatorios por WhatsApp/SMS'),
      g('Staff', 'Calendario de ocupación (día/semana/mes)', 'Check-in / check-out', 'Reservas manuales', 'Bloqueo de fechas'),
      g('Administrador', 'Gestión de recursos y capacidad', 'Tarifas por temporada', 'Políticas de cancelación', 'Reportes de ocupación e ingresos', ...ADMIN_CORE.slice(1)),
    ],
    integrations: ['stripe', 'email', 'whatsapp', 'google'],
    entities: ['users', 'resources (habitaciones/servicios)', 'resource_types', 'rates', 'seasons', 'availability_blocks', 'bookings', 'booking_guests', 'payments', 'cancellation_policies'],
    stackHint: 'Next.js + PostgreSQL (restricciones de exclusión para evitar solapamientos).',
    domainNotes: ['Evitar dobles reservas con bloqueo transaccional o constraint de exclusión sobre rangos de fechas.', 'Zonas horarias explícitas en todas las fechas.'],
  },
  {
    id: 'invoicing',
    label: 'Sistema de facturación',
    category: 'sistemas',
    summary: 'Emisión de facturas, cotizaciones, clientes y pagos.',
    keywords: ['facturacion', 'facturas', 'factura electronica', 'cotizaciones'],
    needsDb: true,
    seo: 'low',
    roles: ['Facturador', 'Contador', 'Administrador'],
    featureGroups: [
      g('Facturación', 'Clientes', 'Productos/servicios con impuestos', 'Cotizaciones convertibles en factura', 'Facturas con numeración consecutiva', 'PDF de factura y envío por email', 'Registro de pagos parciales', 'Notas crédito / anulaciones', 'Facturas recurrentes', '+Facturación electrónica según el país'),
      g('Reportes', 'Cuentas por cobrar y antigüedad de saldos', 'Ventas por periodo', 'Impuestos por periodo', 'Exportación CSV'),
      g('Administración', ...ADMIN_CORE, 'Datos fiscales de la empresa'),
    ],
    integrations: ['email', 'stripe', 'external_api'],
    entities: ['users', 'companies', 'customers', 'items', 'taxes', 'quotes', 'invoices', 'invoice_lines', 'payments', 'credit_notes', 'number_sequences'],
    stackHint: 'Laravel o Next.js + PostgreSQL; cálculo monetario con decimales exactos.',
    domainNotes: ['Importes con tipo decimal exacto (nunca float).', 'La factura electrónica legal (p. ej., DIAN, SAT) requiere un proveedor tecnológico autorizado: integrarlo solo con credenciales y documentación oficiales.'],
  },
  {
    id: 'education',
    label: 'Sistema educativo',
    category: 'sistemas',
    summary: 'Gestión académica: estudiantes, cursos, notas y asistencia.',
    keywords: ['colegio', 'escuela', 'academico', 'notas', 'calificaciones', 'asistencia', 'sistema educativo'],
    needsDb: true,
    seo: 'low',
    roles: ['Estudiante', 'Acudiente', 'Docente', 'Coordinador', 'Administrador'],
    featureGroups: [
      g('Académico', 'Estudiantes y matrículas', 'Grados, grupos y asignaturas', 'Docentes y carga académica', 'Registro de calificaciones por periodo', 'Asistencia', 'Boletines en PDF', 'Horarios'),
      g('Comunicación', 'Circulares y anuncios', 'Mensajería docente–acudiente', 'Notificaciones'),
      g('Administración', ...ADMIN_CORE, 'Años lectivos y periodos'),
    ],
    integrations: ['email', 'whatsapp'],
    entities: ['users', 'students', 'guardians', 'teachers', 'grades', 'groups', 'subjects', 'enrollments', 'periods', 'scores', 'attendance', 'announcements'],
    stackHint: 'Laravel o Next.js + PostgreSQL con permisos por rol muy definidos.',
    domainNotes: ['Datos de menores: privacidad reforzada y acceso mínimo necesario.'],
  },
  {
    id: 'lms',
    label: 'LMS',
    category: 'sistemas',
    summary: 'Plataforma de cursos online con lecciones, evaluaciones y certificados.',
    keywords: ['lms', 'plataforma educativa', 'cursos online', 'e-learning', 'elearning', 'academia online', 'clases'],
    needsDb: true,
    seo: 'medium',
    roles: ['Estudiante', 'Instructor', 'Administrador'],
    featureGroups: [
      g('Estudiante', ...AUTH.slice(0, 4), 'Catálogo de cursos', 'Inscripción gratuita o de pago', 'Reproductor de lecciones (video, texto, archivos)', 'Progreso por curso y lección', 'Cuestionarios con calificación automática', 'Certificado PDF al completar', 'Comentarios / preguntas por lección', '+Gamificación (insignias, rachas)'),
      g('Instructor', 'Creación de cursos con módulos y lecciones', 'Subida de videos y recursos', 'Banco de preguntas', 'Seguimiento de estudiantes', 'Ingresos (si hay cursos de pago)'),
      g('Administrador', 'Aprobación de cursos', 'Gestión de instructores y estudiantes', 'Ventas y cupones', ...ADMIN_CORE.slice(1)),
    ],
    integrations: ['stripe', 'email'],
    entities: ['users', 'courses', 'modules', 'lessons', 'lesson_resources', 'enrollments', 'lesson_progress', 'quizzes', 'questions', 'quiz_attempts', 'certificates', 'orders'],
    stackHint: 'Next.js + PostgreSQL + almacenamiento/streaming de video con un proveedor dedicado.',
    domainNotes: ['El video se sirve desde un proveedor de streaming o almacenamiento con URLs firmadas; no desde el servidor de la app.'],
  },
  {
    id: 'inventory',
    label: 'Sistema de inventario',
    category: 'sistemas',
    summary: 'Control de existencias, entradas, salidas y almacenes.',
    keywords: ['inventario', 'stock', 'almacen', 'bodega', 'existencias'],
    needsDb: true,
    seo: 'low',
    roles: ['Operario', 'Jefe de bodega', 'Administrador'],
    featureGroups: [
      g('Inventario', 'Productos con SKU y código de barras', 'Almacenes y ubicaciones', 'Entradas, salidas y transferencias', 'Kardex por producto', 'Alertas de stock mínimo', 'Inventario físico y ajustes', '+Lotes y vencimientos', '+Escaneo con cámara del móvil'),
      g('Reportes', 'Valorización del inventario', 'Rotación de productos', 'Exportación CSV'),
      g('Administración', ...ADMIN_CORE, 'Proveedores'),
    ],
    integrations: ['email', 'webhooks'],
    entities: ['users', 'products', 'categories', 'warehouses', 'locations', 'stock_levels', 'stock_movements', 'suppliers', 'adjustments'],
    stackHint: 'Next.js o Laravel + PostgreSQL; movimientos inmutables y stock derivado.',
    domainNotes: ['El stock se deriva de movimientos inmutables; los ajustes generan movimientos, nunca ediciones directas.'],
  },
  {
    id: 'tickets',
    label: 'Sistema de tickets',
    category: 'sistemas',
    summary: 'Mesa de ayuda con tickets, prioridades, SLA y base de conocimiento.',
    keywords: ['tickets', 'soporte', 'mesa de ayuda', 'helpdesk', 'incidencias'],
    needsDb: true,
    seo: 'low',
    roles: ['Cliente', 'Agente', 'Supervisor', 'Administrador'],
    featureGroups: [
      g('Cliente', ...AUTH.slice(0, 3), 'Crear ticket con adjuntos', 'Seguimiento y respuestas', 'Valoración de la atención', 'Base de conocimiento pública'),
      g('Agentes', 'Bandeja con filtros y vistas', 'Asignación y reasignación', 'Prioridades y estados', 'Respuestas predefinidas', 'Notas internas', 'SLA con alertas de vencimiento'),
      g('Administración', 'Categorías y reglas de asignación', 'Reportes de tiempos de respuesta y resolución', ...ADMIN_CORE.slice(1)),
    ],
    integrations: ['email', 'whatsapp', 'telegram', 'webhooks'],
    entities: ['users', 'tickets', 'ticket_messages', 'attachments', 'categories', 'priorities', 'sla_policies', 'kb_articles', 'satisfaction_ratings'],
    stackHint: 'Next.js o Laravel + PostgreSQL + colas para notificaciones.',
    domainNotes: ['Los adjuntos se validan por tipo y tamaño y se guardan fuera del directorio público.'],
  },
  {
    id: 'business_mgmt',
    label: 'Sistema de gestión empresarial',
    category: 'sistemas',
    summary: 'Gestión de operaciones internas: proyectos, tareas, empleados y documentos.',
    keywords: ['gestion empresarial', 'gestion de proyectos', 'tareas', 'empleados', 'recursos humanos'],
    needsDb: true,
    seo: 'low',
    roles: ['Empleado', 'Líder de equipo', 'Gerente', 'Administrador'],
    featureGroups: [
      g('Operación', 'Proyectos y tareas (lista y Kanban)', 'Asignación y fechas límite', 'Registro de tiempo', 'Documentos compartidos con permisos', 'Calendario', 'Comentarios y menciones'),
      g('Personas', 'Directorio de empleados', 'Solicitudes de vacaciones/permisos con aprobación', '+Evaluaciones de desempeño'),
      g('Administración', ...ADMIN_CORE, 'Departamentos'),
    ],
    integrations: ['email', 'google', 'webhooks'],
    entities: ['users', 'departments', 'projects', 'tasks', 'time_entries', 'documents', 'comments', 'leave_requests', 'audit_logs'],
    stackHint: 'Next.js + PostgreSQL.',
    domainNotes: ['Notificaciones en la app y por email ante asignaciones y menciones.'],
  },
  {
    id: 'affiliates',
    label: 'Sistema de afiliados',
    category: 'sistemas',
    summary: 'Programa de afiliados con enlaces de referido, comisiones y pagos.',
    keywords: ['afiliados', 'referidos', 'comisiones', 'programa de afiliacion'],
    needsDb: true,
    seo: 'low',
    roles: ['Afiliado', 'Administrador'],
    featureGroups: [
      g('Afiliado', ...AUTH.slice(0, 4), 'Enlaces de referido únicos', 'Panel de clics, conversiones y comisiones', 'Materiales promocionales', 'Solicitud de pago', 'Historial de pagos'),
      g('Administrador', 'Aprobación de afiliados', 'Reglas de comisión (porcentaje/fijo, por producto)', 'Validación de conversiones', 'Pagos a afiliados', 'Detección de fraude básica', ...ADMIN_CORE.slice(1)),
    ],
    integrations: ['webhooks', 'email', 'paypal'],
    entities: ['users', 'affiliates', 'referral_links', 'clicks', 'conversions', 'commissions', 'payouts', 'commission_rules'],
    stackHint: 'Next.js + PostgreSQL; tracking con cookie de primera parte y webhooks de conversión.',
    domainNotes: ['Atribución con ventana configurable; conversiones confirmadas por webhook del sistema de ventas.'],
  },
  {
    id: 'users_roles',
    label: 'Sistema de usuarios y roles',
    category: 'sistemas',
    summary: 'Gestión centralizada de identidades, roles, permisos y auditoría.',
    keywords: ['usuarios y roles', 'permisos', 'control de acceso', 'rbac', 'autenticacion'],
    needsDb: true,
    seo: 'low',
    roles: ['Usuario', 'Administrador de usuarios', 'Superadministrador'],
    featureGroups: [
      g('Usuarios', ...AUTH, 'Gestión de sesiones activas', 'Historial de inicios de sesión'),
      g('Administración', 'CRUD de usuarios', 'Roles y permisos granulares (RBAC)', 'Invitaciones por email', 'Bloqueo y desbloqueo de cuentas', 'Auditoría de cambios', '+Políticas de contraseña configurables', '+API con tokens personales'),
    ],
    integrations: ['email', 'google'],
    entities: ['users', 'roles', 'permissions', 'role_permissions', 'user_roles', 'sessions', 'invitations', 'login_events', 'audit_logs'],
    stackHint: 'Next.js o Laravel + PostgreSQL; librerías de autenticación probadas.',
    domainNotes: ['Principio de mínimo privilegio y verificación de permisos en el servidor en cada endpoint.'],
  },

  // ============================== SAAS ==============================
  {
    id: 'saas_business',
    label: 'SaaS empresarial',
    category: 'saas',
    summary: 'Software como servicio para empresas con organizaciones, equipos y facturación.',
    keywords: ['saas', 'software como servicio', 'plataforma para empresas', 'b2b'],
    needsDb: true,
    seo: 'medium',
    roles: ['Propietario de organización', 'Administrador de organización', 'Miembro', 'Superadmin de plataforma'],
    featureGroups: [
      g('Cuenta', ...AUTH, 'Organizaciones y cambio de organización', 'Invitación de miembros por email', 'Roles por organización'),
      g('Producto', 'Módulo principal del negocio (definir según la idea)', 'Dashboard con métricas de uso', 'Búsqueda global', 'Notificaciones en la app', 'Exportación de datos', '+API pública con claves'),
      g('Facturación', 'Planes y suscripción', 'Periodo de prueba', 'Portal de facturación', 'Límites por plan'),
      g('Superadmin', 'Gestión de organizaciones', 'Métricas MRR y uso', 'Soporte: impersonación auditada', 'Feature flags'),
    ],
    integrations: ['stripe', 'email', 'webhooks', 'google'],
    entities: ['users', 'organizations', 'memberships', 'invitations', 'plans', 'subscriptions', 'usage_records', 'api_keys', 'audit_logs', 'feature_flags'],
    stackHint: 'Next.js + TypeScript + PostgreSQL + Stripe Billing; multi-tenant por organization_id.',
    domainNotes: ['Aislamiento multi-tenant: toda consulta filtra por organización (idealmente con Row Level Security).', 'Landing de marketing + app autenticada separadas.'],
  },
  {
    id: 'saas_subscriptions',
    label: 'SaaS con suscripciones',
    category: 'saas',
    summary: 'SaaS con planes de pago recurrentes, pruebas y límites por plan.',
    keywords: ['saas con suscripcion', 'planes de pago', 'freemium', 'pago mensual'],
    needsDb: true,
    seo: 'medium',
    roles: ['Usuario', 'Administrador de cuenta', 'Superadmin'],
    featureGroups: [
      g('Cuenta', ...AUTH, 'Onboarding guiado'),
      g('Producto', 'Funcionalidad principal (definir según la idea)', 'Dashboard', 'Límites de uso visibles', 'Notificaciones'),
      g('Facturación', 'Página de precios', 'Checkout de suscripción', 'Upgrade/downgrade con prorrateo', 'Cancelación y reactivación', 'Facturas', 'Gestión de cobros fallidos', 'Plan gratuito o prueba'),
      g('Superadmin', 'Métricas MRR, churn, conversión', 'Gestión de planes', 'Usuarios y cuentas'),
    ],
    integrations: ['stripe', 'email', 'webhooks'],
    entities: ['users', 'accounts', 'plans', 'subscriptions', 'invoices', 'usage_records', 'webhook_events'],
    stackHint: 'Next.js + PostgreSQL + Stripe Billing.',
    domainNotes: ['Los límites por plan se aplican en el servidor (middleware de autorización por plan).'],
  },
  {
    id: 'saas_multiuser',
    label: 'SaaS multiusuario',
    category: 'saas',
    summary: 'SaaS con equipos colaborando sobre los mismos datos.',
    keywords: ['multiusuario', 'colaborativo', 'equipos', 'trabajo en equipo'],
    needsDb: true,
    seo: 'medium',
    roles: ['Propietario', 'Editor', 'Lector', 'Superadmin'],
    featureGroups: [
      g('Colaboración', ...AUTH.slice(0, 4), 'Espacios de trabajo', 'Invitaciones y roles por espacio', 'Comentarios y menciones', 'Historial de actividad', '+Edición en tiempo real', '+Presencia de usuarios'),
      g('Producto', 'Funcionalidad principal (definir según la idea)', 'Dashboard', 'Notificaciones'),
      g('Administración', ...ADMIN_CORE),
    ],
    integrations: ['email', 'google', 'webhooks'],
    entities: ['users', 'workspaces', 'workspace_members', 'invitations', 'comments', 'activity_log', 'notifications'],
    stackHint: 'Next.js + PostgreSQL; WebSockets o servicio realtime si hay colaboración en vivo.',
    domainNotes: ['Permisos por recurso dentro del espacio de trabajo.'],
  },
  {
    id: 'saas_multitenant',
    label: 'SaaS multiempresa',
    category: 'saas',
    summary: 'SaaS multi-tenant con empresas aisladas, subdominios y configuración propia.',
    keywords: ['multiempresa', 'multi empresa', 'multitenant', 'multi-tenant', 'multi tenant', 'marca blanca'],
    needsDb: true,
    seo: 'low',
    roles: ['Superadmin', 'Admin de empresa', 'Usuario de empresa'],
    featureGroups: [
      g('Tenants', 'Alta de empresas (tenants)', 'Subdominio o dominio propio por empresa', 'Branding por empresa (logo, colores)', 'Configuración por empresa', 'Usuarios y roles por empresa'),
      g('Producto', 'Funcionalidad principal (definir según la idea)', 'Dashboard por empresa', 'Exportación de datos'),
      g('Plataforma', 'Panel superadmin', 'Planes y facturación por empresa', 'Métricas globales', 'Auditoría'),
    ],
    integrations: ['stripe', 'email', 'webhooks'],
    entities: ['tenants', 'tenant_domains', 'tenant_settings', 'users', 'tenant_users', 'roles', 'plans', 'subscriptions', 'audit_logs'],
    stackHint: 'Next.js o Laravel + PostgreSQL con tenant_id + Row Level Security, o esquema por tenant justificado.',
    domainNotes: ['Estrategia de aislamiento explícita y probada con tests que intenten acceder a datos de otro tenant.'],
  },
  {
    id: 'dashboard',
    label: 'Dashboard',
    category: 'saas',
    summary: 'Panel de analítica y KPIs con gráficos, filtros e informes.',
    keywords: ['dashboard', 'analitica', 'kpis', 'reportes', 'metricas', 'business intelligence'],
    needsDb: true,
    seo: 'low',
    roles: ['Lector', 'Analista', 'Administrador'],
    featureGroups: [
      g('Analítica', 'KPIs principales con variación vs. periodo anterior', 'Gráficos (líneas, barras, distribución)', 'Filtros por fecha y dimensiones', 'Tablas con paginación, orden y búsqueda', 'Exportación CSV/PDF', '+Dashboards personalizables', '+Alertas por umbral'),
      g('Datos', 'Ingesta de datos (API, CSV o base de datos existente)', 'Agregaciones precalculadas para rendimiento', 'Comparativa entre periodos', 'Drill-down de cada KPI hasta el detalle de registros', '+Informes programados por email'),
      g('Administración', ...ADMIN_CORE.slice(1)),
    ],
    integrations: ['external_api', 'email'],
    entities: ['users', 'data_sources', 'metrics', 'daily_aggregates', 'dashboards', 'widgets', 'alerts'],
    stackHint: 'Next.js + PostgreSQL con vistas materializadas o agregados precalculados.',
    domainNotes: ['Todos los números provienen de datos reales; si no hay datos, mostrar estados vacíos, nunca cifras inventadas.'],
  },
  {
    id: 'api',
    label: 'API',
    category: 'saas',
    summary: 'API REST o GraphQL documentada, versionada y segura.',
    keywords: ['api', 'backend', 'endpoints', 'microservicio', 'rest api'],
    needsDb: true,
    seo: 'low',
    roles: ['Consumidor de la API', 'Administrador'],
    featureGroups: [
      g('API', 'Autenticación (API keys o OAuth2/JWT)', 'CRUD de los recursos principales', 'Paginación, filtros y ordenación', 'Validación de entrada con errores consistentes', 'Versionado (/v1)', 'Documentación OpenAPI interactiva', 'Rate limiting por clave', 'Webhooks salientes', '+Idempotency-Key en operaciones de escritura'),
      g('Gestión', 'Panel para generar y revocar claves', 'Métricas de uso por clave', 'Logs de peticiones', 'Health check y métricas del servicio', 'Errores con formato uniforme (Problem Details)', '+Entorno sandbox para integradores'),
    ],
    integrations: ['webhooks'],
    entities: ['api_clients', 'api_keys', 'request_logs', 'webhook_subscriptions', 'webhook_deliveries', '(recursos del dominio)'],
    stackHint: 'Node.js (Fastify/NestJS) o Laravel + PostgreSQL, con OpenAPI generado desde los esquemas.',
    domainNotes: ['Formato de error uniforme (p. ej., RFC 9457 Problem Details).', 'Tests de contrato para cada endpoint.'],
  },
  {
    id: 'saas_plans',
    label: 'Plataforma con planes',
    category: 'saas',
    summary: 'Plataforma con planes y funcionalidades desbloqueadas por nivel.',
    keywords: ['plataforma con planes', 'planes basico pro', 'niveles de plan', 'plan premium'],
    needsDb: true,
    seo: 'medium',
    roles: ['Usuario gratuito', 'Usuario de pago', 'Administrador'],
    featureGroups: [
      g('Usuarios', ...AUTH.slice(0, 4), 'Comparativa de planes', 'Upgrade dentro de la app', 'Funciones bloqueadas con mensaje de upgrade'),
      g('Producto', 'Funcionalidad principal (definir según la idea)', 'Medición de uso por plan'),
      g('Administración', 'Gestión de planes y entitlements', 'Suscripciones', 'Métricas de conversión', ...ADMIN_CORE.slice(1, 3)),
    ],
    integrations: ['stripe', 'email'],
    entities: ['users', 'plans', 'plan_features', 'subscriptions', 'usage_records'],
    stackHint: 'Next.js + PostgreSQL + Stripe Billing; entitlements centralizados.',
    domainNotes: ['Una única función de entitlements decide qué puede hacer cada plan (no condiciones dispersas).'],
  },

  // ============================== APPS ==============================
  {
    id: 'pwa',
    label: 'PWA',
    category: 'apps',
    summary: 'Aplicación web progresiva instalable, con soporte offline y notificaciones.',
    keywords: ['pwa', 'progresiva', 'instalable', 'offline'],
    needsDb: true,
    seo: 'medium',
    roles: ['Usuario', 'Administrador'],
    featureGroups: [
      g('App', 'Manifest con iconos y pantalla de inicio', 'Service worker con estrategia de caché', 'Funcionamiento offline de las vistas clave', 'Sincronización en segundo plano al recuperar conexión', 'Notificaciones push (con permiso)', 'Funcionalidad principal (definir según la idea)', ...AUTH.slice(0, 3)),
      g('Administración', ...ADMIN_CORE.slice(0, 3)),
    ],
    integrations: ['firebase'],
    entities: ['users', 'push_subscriptions', '(entidades del dominio)'],
    stackHint: 'Next.js o Vite + React con un service worker (Workbox) y API propia.',
    domainNotes: ['Probar instalación y modo offline en Android e iOS.'],
    pwa: true,
  },
  {
    id: 'webapp',
    label: 'Aplicación web',
    category: 'apps',
    summary: 'Aplicación web completa con autenticación y funcionalidad de negocio.',
    keywords: ['aplicacion web', 'app web', 'web app', 'webapp', 'plataforma web'],
    needsDb: true,
    seo: 'low',
    roles: ['Usuario', 'Administrador'],
    featureGroups: [
      g('Usuarios', ...AUTH, 'Funcionalidad principal (definir según la idea)', 'Búsqueda', 'Notificaciones'),
      g('Administración', ...ADMIN_CORE),
    ],
    integrations: ['email'],
    entities: ['users', 'roles', 'audit_logs', '(entidades del dominio)'],
    stackHint: 'Next.js + TypeScript + PostgreSQL.',
    domainNotes: [],
  },
  {
    id: 'android',
    label: 'Android',
    category: 'apps',
    summary: 'Aplicación nativa Android.',
    keywords: ['android', 'app movil', 'aplicacion movil', 'play store', 'apk'],
    needsDb: true,
    seo: 'low',
    roles: ['Usuario', 'Administrador (backend)'],
    featureGroups: [
      g('App', 'Onboarding', ...AUTH.slice(0, 4), 'Funcionalidad principal (definir según la idea)', 'Notificaciones push', 'Modo offline con caché local', 'Ajustes y tema claro/oscuro'),
      g('Backend', 'API para la app', 'Panel administrativo web', 'Gestión de usuarios'),
    ],
    integrations: ['firebase'],
    entities: ['users', 'devices', 'push_tokens', '(entidades del dominio)'],
    stackHint: 'Kotlin + Jetpack Compose + arquitectura MVVM, Room para caché local y Retrofit/Ktor para la API.',
    domainNotes: ['Material Design 3, soporte de distintos tamaños de pantalla y modo oscuro.', 'Generar APK/AAB firmado con instrucciones; claves fuera del repositorio.'],
  },
  {
    id: 'android_tv',
    label: 'Android TV',
    category: 'apps',
    summary: 'Aplicación para Android TV con navegación por mando a distancia.',
    keywords: ['android tv', 'smart tv', 'televisor', 'tv box', 'google tv'],
    needsDb: false,
    seo: 'low',
    roles: ['Espectador'],
    featureGroups: [
      g('App TV', 'Navegación completa con D-pad (foco visible)', 'Filas de contenido tipo carrusel', 'Pantalla de detalle', 'Reproductor de video con controles de mando', 'Búsqueda (incluida por voz si aplica)', 'Perfiles', '+Continuar viendo'),
    ],
    integrations: ['external_api'],
    entities: ['(catálogo remoto)', 'watch_progress (local)', 'profiles (local)'],
    stackHint: 'Kotlin + Jetpack Compose for TV (androidx.tv) + Media3/ExoPlayer.',
    domainNotes: ['Diseñar para 10 pies: tipografía grande, foco muy visible y zonas seguras de overscan.', 'Declarar leanback launcher y banner en el manifest.'],
  },
  {
    id: 'admin_panel',
    label: 'Panel administrativo',
    category: 'apps',
    summary: 'Back-office para gestionar datos y operaciones de un negocio.',
    keywords: ['panel administrativo', 'panel de administracion', 'backoffice', 'back office', 'admin panel'],
    needsDb: true,
    seo: 'low',
    roles: ['Operador', 'Supervisor', 'Administrador'],
    featureGroups: [
      g('Panel', ...ADMIN_CORE, 'CRUD de las entidades del negocio', 'Tablas con filtros, orden, búsqueda y paginación del servidor', 'Acciones masivas', 'Importación/exportación CSV', 'Formularios con validación', 'Búsqueda global (Ctrl+K)', 'Vista de detalle con historial de cambios por registro', 'Filtros guardados por usuario', 'Notificaciones internas', '+Adjuntos de archivos por registro'),
    ],
    integrations: ['email'],
    entities: ['users', 'roles', 'permissions', 'audit_logs', '(entidades del negocio)'],
    stackHint: 'Next.js + TypeScript + PostgreSQL con componentes de tabla y formularios robustos.',
    domainNotes: ['Toda acción destructiva pide confirmación y queda auditada.'],
  },
  {
    id: 'app_api',
    label: 'Aplicación con API',
    category: 'apps',
    summary: 'Frontend web + API propia desacoplada, preparada para otros clientes (móvil).',
    keywords: ['app con api', 'frontend y backend', 'api y frontend', 'desacoplado'],
    needsDb: true,
    seo: 'low',
    roles: ['Usuario', 'Administrador'],
    featureGroups: [
      g('Frontend', ...AUTH.slice(0, 4), 'Funcionalidad principal (definir según la idea)', 'Manejo de estados de carga y error de la API'),
      g('API', 'Endpoints versionados', 'Autenticación con tokens (access + refresh)', 'Documentación OpenAPI', 'Rate limiting', 'CORS restringido'),
      g('Administración', ...ADMIN_CORE.slice(0, 3)),
    ],
    integrations: ['webhooks'],
    entities: ['users', 'refresh_tokens', 'audit_logs', '(entidades del dominio)'],
    stackHint: 'Monorepo con frontend (React/Next.js) y API (Node.js/NestJS o Laravel) + PostgreSQL.',
    domainNotes: ['Tipos compartidos entre API y frontend (o cliente generado desde OpenAPI).'],
  },
  {
    id: 'streaming',
    label: 'Plataforma de streaming',
    category: 'apps',
    summary: 'Streaming de video o audio con catálogo, suscripciones y reproductor.',
    keywords: ['streaming', 'peliculas', 'series', 'video bajo demanda', 'vod', 'tipo netflix', 'musica', 'podcast'],
    needsDb: true,
    seo: 'medium',
    roles: ['Espectador', 'Suscriptor', 'Editor de catálogo', 'Administrador'],
    featureGroups: [
      g('Espectador', ...AUTH.slice(0, 4), 'Catálogo por categorías y carruseles', 'Ficha de contenido', 'Reproductor adaptativo (HLS) con calidad automática', 'Continuar viendo', 'Mi lista', 'Búsqueda', 'Perfiles por cuenta', 'Suscripción de pago'),
      g('Administración', 'Gestión de catálogo, temporadas y episodios', 'Subida y transcodificación mediante proveedor de video', 'Gestión de suscripciones', 'Analítica de reproducción', ...ADMIN_CORE.slice(1, 3)),
    ],
    integrations: ['stripe', 'email', 'external_api'],
    entities: ['users', 'profiles', 'titles', 'seasons', 'episodes', 'genres', 'video_assets', 'watch_progress', 'watchlists', 'subscriptions'],
    stackHint: 'Next.js + PostgreSQL + proveedor de video (transcodificación HLS y CDN) + Stripe Billing.',
    domainNotes: ['Nunca servir video desde el servidor de la app: usar proveedor de video con CDN y URLs firmadas.', 'Respetar derechos de contenido: solo material con licencia.'],
  },

  // ============================== CUSTOM ==============================
  {
    id: 'custom',
    label: 'Proyecto personalizado',
    category: 'custom',
    summary: 'Cualquier proyecto que no encaje en las categorías anteriores.',
    keywords: [],
    needsDb: true,
    seo: 'medium',
    roles: ['Usuario', 'Administrador'],
    featureGroups: [
      g('Usuarios', ...AUTH.slice(0, 4), 'Funcionalidad principal (definir según la idea)'),
      g('Administración', ...ADMIN_CORE.slice(0, 3)),
    ],
    integrations: [],
    entities: ['users', '(entidades del dominio)'],
    stackHint: 'Elegir el stack según los requisitos y justificarlo.',
    domainNotes: [],
  },
];

export const TYPE_BY_ID: Record<string, ProjectType> = Object.fromEntries(PROJECT_TYPES.map((t) => [t.id, t]));

export function getProjectType(id: string): ProjectType {
  return TYPE_BY_ID[id] ?? TYPE_BY_ID.custom;
}

export function typesByCategory(category: CategoryId): ProjectType[] {
  return PROJECT_TYPES.filter((t) => t.category === category);
}

export function categoryLabel(id: CategoryId): string {
  return CATEGORIES.find((c) => c.id === id)?.label ?? id;
}
